package BufferApp;


/**
* BufferApp/Buffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* domingo 22 de febrero de 2015 18H46' CET
*/

public interface Buffer extends BufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Buffer
