package BufferApp;


/**
* BufferApp/Buffer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* Friday, April 2, 2021 11:16:11 AM EDT
*/

public interface Buffer extends BufferOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Buffer
