package BufferApp;


/**
* BufferApp/BufferOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Buffer.idl
* Friday, April 2, 2021 11:16:11 AM EDT
*/

public interface BufferOperations 
{
  boolean put (String elemento);
  boolean get (org.omg.CORBA.StringHolder elemento);
  boolean read (org.omg.CORBA.StringHolder elemento);
  boolean readAll (org.omg.CORBA.StringHolder elemento);
  boolean getBufferLength (org.omg.CORBA.StringHolder elemento);
  boolean setBufferLength (String elemento);
  void shutdown ();
} // interface BufferOperations
